planning_frame:
    - value: "world"
end_effector_frame:
    - value: "ee_link"
planner_id:
    - value: "RRTConnectkConfigDefault"
home_position:
    - value: [-5.926, -1.607, 2.056, -3.579, -1.900, -0.015]
home_pose:
    - xyz: [0.371, 0.247, 1.601]
    - quaternion: [-0.010, 0.004, 0.016, 1.000]